package spring.project.Daily.Mind.entity;

import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;


@Document(collection = "journal_entries")
@Data

@Schema(name = "JournalEntry", description = "A user's journal entry containing title, content and date")
public class JournalEntry {

    @Id
    @Schema(description = "ObjectId generated by MongoDB", example = "656f4a3b2f1e8a6f4b2c9d7e", accessMode = Schema.AccessMode.READ_ONLY)
    private ObjectId id;

    @Schema(description = "Title of the journal entry", example = "My day at the beach")
    private String title;

    @Schema(description = "Content of the journal entry", example = "I had a great walk on the beach today...")
    private String content;

    @Schema(description = "Timestamp when the entry was created", type = "string", format = "date-time", accessMode = Schema.AccessMode.READ_ONLY)
    private LocalDateTime date;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private List<String> tags;

    public String getId() {
        return id == null ? null : id.toHexString();
    }

    public ObjectId getById() {
        return id;
    }
}
